spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/brainsci?characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    remote:
      secret: myscret
  session:
    store-type: none
    timeout: 72h

filesys:
  # filesys.dir以/结尾,不然SecurityConfig无法添加此资源
  dir: ./dist/
  path-matlab: /usr/bin/matlab
  path-python: /usr/bin/python

spring:
  mail:
    host: smtp.163.com  	#邮箱服务器地址
    username: xxx@163.com   #邮箱账号
    password: xxx			#邮箱密码
    default-encoding: utf-8	#默认编码
#邮件发件人
mail:
  fromMail:
    addr: xxx@163.com



