spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/brainsci?characterEncoding=utf-8&useSSL=false
    username: root
    password: 187dezhu
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    remote:
      secret: myscret
  session:
    store-type: none
    timeout: 72h
  mail:
    host: smtp.csu.edu.cn  	#邮箱服务器地址
    username: aknifejackzhmolong   #邮箱账号
    password: 187dezhu			#邮箱密码
    default-encoding: utf-8	#默认编码

bsci:
  processor:
    handlers:
      - id: gretna
        boot: python
        params: D:/code/python/test.py
        deleteTaget: data
filesys:
  # filesys.dir以/结尾,不然SecurityConfig无法添加此资源
  dir: ./dist/
  path-matlab: /usr/local/MATLAB/R2018b/bin/matlab

#邮件发件人
mail:
  fromMail:
    addr: aknifejackzhmolong@csu.edu.cn


