spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/brainsci?characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    remote:
      secret: myscret
  session:
    store-type: none
    timeout: 72h
  mail:
    host: smtp.csu.edu.cn    #邮箱服务器地址
    username: xyzxzj   #邮箱账号
    password: xyz673792            #邮箱密码
    default-encoding: utf-8    #默认编码

bsci:
  processor:
    handlers:
      - id: fmri
        boot: python
        params: [/home/cdj/brainnet/python_pipeline/fmri_pipeline_parameter.py,<basepath>,<jsonparam>]
        replace-all: [/public/fmri,./dist/public/fmri]
#        output-taget: ./working
        # 当使用<outputpath>时需设置output-taget
      - id: smri
        boot: python
        params: [/home/cdj/brainnet/python_pipeline/T1_surface/freesurfer_recon.py,<basepath>,<jsonparam>]
#        output-taget: ./working
      - id: smriParallel
        boot: python
        params: [/home/cdj/brainnet/python_pipeline/T1_surface/freesurfer_recon_parallel.py,<basepath>,<jsonparam>]
#        output-taget: ./working
      - id: dti
        boot: python
        params: [/home/cdj/brainnet/python_pipeline/dwi_dti/dwi_pipeline_parameter.py,<basepath>,<jsonparam>]
        replace-all: [/public/DTI,./dist/public/DTI]
#        output-taget: ./working
filesys:
  # filesys.dir以/结尾,不然SecurityConfig无法添加此资源
  dir: ./dist/
  path-matlab: /usr/bin/matlab
  path-python: /usr/bin/python

#邮件发件人
mail:
  fromMail:
    addr: xyzxzj@csu.edu.cn



